#!/bin/sh

set -e

cd /tmp 

curl -L https://github.com/opencontainers/runc/archive/v${RUNC_VERSION}.tar.gz | tar -xz 
cd runc-${RUNC_VERSION}
make BUILDTAGS="selinux"

tar -Jcf /artifacts/runc-centos-71.tar.xz runc